name: Publish

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependency
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/@pedagogy-square-helper/script.user.js
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
